[phases.setup]
nixPkgs = ["php82", "php82Extensions.exif", "git"]

[phases.install]
cmds = [
    "git submodule update --init --recursive",
    "composer install --optimize-autoloader --no-scripts --no-interaction --ignore-platform-req=ext-exif",
    "yarn install --frozen-lockfile"
]

[phases.build]
cmds = [
    "yarn build",
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan view:cache"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=${PORT:-8080}"
